import '@/app/globals.css'
import { open_sans } from '@/styles/fonts/font'
import type { Metadata } from 'next'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={`${open_sans.className}`}>
            {children}
      </body>
    </html>  
  )
}
