import '@/app/globals.css'
import { open_sans } from '@/styles/fonts/font'
import { AuthProvider } from '@/context/auth.context'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <AuthProvider >
      <html lang="en">
        <body className={`${open_sans.className}`} id='rootmodal'>
          {children}
          {/* <AuthGuard>{children}</AuthGuard> */}
        </body>
      </html>
    </AuthProvider>
  )
}
